### ISSUE TITLE
Useful blog for OSX El-Captian Phoenix 0.17 upgrade to 1.0.3 Postgres-ecto-create issue

### ISSUE THREAD

**Issue by yeongsheng-tan** [CultivateHQ/seat_saver#1]
##### OSX El-Captian Phoenix 0.17 upgrade to 1.0.3 Postgres-ecto-create issue

Thought this might be useful for people following the tutorial attempting to get Phoenix 1.0.3 Postgresql 9.x up and running on OSX El-Captian hitting postgres-ecto-create permission related warnings/errors when upgrading from an existing Phoenix 0.17 install.

http://blog.jasonkim.ca/blog/2015/09/01/setting-up-phoenix-1-dot-0-on-mac-os-x-yosemite/

e.g. 
- (Mix) The database for SeatSaver.Repo couldn't be created, reason given: psql: FATAL:  role "postgres" does not exist
- (Mix) The database for SeatSaver.Repo couldn't be created, reason given: psql: FATAL:  role "postgres" is not permitted to log in

**Comment by urfolomeus** [comment]
Thanks @yeongsheng-tan. Much appreciated. Will add it to the Home page. :)

**Comment by urfolomeus** [comment]
Added a gotchas section and put this in. Thanks again.

**Comment by yeongsheng-tan** [comment]
Sweet. :+1:

**Comment by brayhoward** [comment]
Can you post a link to where this blog post lives now @urfolomeus ? The link at the top no longer works.

**Comment by urfolomeus** [comment]
It seems to be available at http://blog.jasonkim.ca/blog/2015/09/02/setting-up-phoenix-1-dot-0-on-mac-os-x-yosemite/
