### ISSUE TITLE
Deploying to Heroku?

### ISSUE THREAD

**Issue by mockdeep** [CultivateHQ/seat_saver#10]
Any advice on how to deploy this to Heroku? In particular, I'm wondering how you would go about getting the Elm code to precompile on deploy.

**Comment by mockdeep** [comment]
Never mind, answered my own question. All that needs to be done is:

``` sh
npm install --save-dev elm
```

Then when you deploy `elm-brunch` handles the precompilation.

**Comment by urfolomeus** [comment]
Thanks for raising @mockdeep.
