### ISSUE TITLE
evancz/elm-html doesn't work with Elm 0.17

### ISSUE THREAD

**Issue by paulbutcher** [CultivateHQ/seat_saver#11]
Apologies if this isn't the best way to report this—I couldn't find any way to comment on your blog?

As I just found out this morning, the `evancz/elm-html` module doesn't work with Elm 0.17 (giving the very cryptic error "Error: Unable to find a set of packages that will work with your constraints."). It's been replaced by `elm-lang/html`.

**Comment by paulbutcher** [comment]
Great tutorial BTW. Thanks!

**Comment by urfolomeus** [comment]
Yeah we're taking a look just now on how the new version of Elm will affect the tutorials. In the meantime, if you want to go through the tutorial, you'll need to drop back to Elm 0.16.

I suspect that a lot of the stuff that we've had to do in the blog to get Phoenix and Elm to speak to each other has now gone away.

Watch this space! :)

**Comment by paulbutcher** [comment]
Thanks for the rapid response. I'll drop back to 0.16 for now and watch this space ;)

**Comment by nathanl** [comment]
How does one drop back to 0.16? http://elm-lang.org/install only gives a way to install the latest.

**Comment by urfolomeus** [comment]
Hi Nathan,

Sorry for the delay in reply. You can also install Elm via NPM. That should give you the option of specifying the version, although I've not actually tried that myself yet (the version that is, not installing via NPM).

**Comment by rogeriomarques** [comment]
I'm setting some time aside to learn both elm and elixir but can certainly wait a bit more. Do you intent to update this (great) tutorial to 0.17 in the near future?

**Comment by urfolomeus** [comment]
I'm hoping to get it updated next week. There have been a few conferences over the last few weeks that I've either been attending, speaking at or helping run, but the last one is Thursday/Friday this week. I'll post here when the update goes out. Thanks for you patience :)

**Comment by rogeriomarques** [comment]
Thank you, I'll wait. Yours is by far the best tutorial on the subject and the only one I've found that goes beyond the "hello world" level. Great resource to the community.

**Comment by rogeriomarques** [comment]
BTW, Elixir 1.3 is coming out soon it seems... maybe taking that into account would be a good idea.

**Comment by GreenHapi** [comment]
@urfolomeus Thank you for this tutorial, for keeping it up to date and for inspiring talk at ElixirConf 2015! Time is the most precious thing one can have and you use it to share knowledge to make developers world better! :)

**Comment by urfolomeus** [comment]
@TheGreenHabi thanks very much. It has very much been my pleasure 😃

**Comment by urfolomeus** [comment]
@paulbutcher @nathanl @rogeriomarques @TheGreenHabi I've finally managed to find the time to get parts 1-6 of the Phoenix-Elm posts released. There's a new repo associated with it to keep things simple -> https://github.com/CultivateHQ/seat_saver-017.

Hopefully it will take me less time to get the rest of the posts done! Thanks for your patience.

**Comment by rogeriomarques** [comment]
Thanks @urfolomeus !
