### ISSUE TITLE
Can't even install packages if Elm 0.17 installed 

### ISSUE THREAD

**Issue by hipertracker** [CultivateHQ/seat_saver#12]
If somebody has installed new Elm 0.17, it can't even install packages for seat_saver. :(
...
cd web/elm
elm package install
Error: Unable to find a set of packages that will work with your constraints.

```
```

**Comment by urfolomeus** [comment]
Sorry for the delay getting back to you. I'm hoping to have time to write an update post this week.

**Comment by urfolomeus** [comment]
Just as a head's up, due to some last minute work coming in I've had to delay the updating to next week. I've updated posts 1 through 6 and they're awaiting someone at Cultivate being available to review before we publish, so not long to wait now!

Thank you for your patience :)

**Comment by fahrradflucht** [comment]
Do you still plan to release the Elm 0.17 updates? I would drop back into 0.16 but if those updates would come soon I would surely wait...

**Comment by urfolomeus** [comment]
Sorry yes. I appreciate its taking a while but I've been swamped with other work. Will get at least parts 1-5 out tomorrow. Possibly 6 too. Thanks for your patience.

**Comment by urfolomeus** [comment]
@Fahrradflucht @hipertracker hi folks. I _finally_ managed to get the blog posts updated (well 1-6 anyway). So sorry to keep you waiting.

I might even have time to get the rest done before the end of the month 😁 

I decided to start a new repo for that one to keep things clean -> https://github.com/CultivateHQ/seat_saver-017
