### ISSUE TITLE
No more signals in 0.17

### ISSUE THREAD

**Issue by ramstein74** [CultivateHQ/seat_saver#14]
Hello i was reading your excellent tutorial ("again") and saw you updated it to elm 0.17
However chapter 7 is about signals and signals are dead in elm 0.17 right?

Thank you

**Comment by urfolomeus** [comment]
I haven't updated past post 6 yet for precisely this reason. I'm trying to figure out whether I should leave post 7 in with a notice about Signals in Elm 0.17 or whether I should remove it altogether for sake of clarity.

AFAICT Signals have not gone from Elm 0.17, they have just been de-emphasized such that you are less likely to need to work with them directly.

**Comment by urfolomeus** [comment]
@ramstein74 I'm going to merge this issue in with #15 as they're essentially the same topic.
