### ISSUE TITLE
Require new OSX elm installer on OSX EL Capitan

### ISSUE THREAD

**Issue by yeongsheng-tan** [CultivateHQ/seat_saver#2]
I am hitting 'permission denied' issue when attempting to install elm core packages in [embedding elm into phoenix steps](https://github.com/CultivateHQ/seat_saver/wiki/2.-Adding-Elm#embedding-elm-into-phoenix)

``` shell
elm package install -y
elm-package: /usr/bin/git: fileAccess: permission denied (Operation not permitted)
```

Solution is provided [here](https://github.com/elm-lang/elm-package/issues/109)
- Updated OSX El-Capitan [Elm installer required](http://install.elm-lang.org/Elm-Platform-0.15.1-el-capitan.pkg)

**Comment by urfolomeus** [comment]
Thanks @yeongsheng-tan. Have added to the gotchas.
