### ISSUE TITLE
Next steps?

### ISSUE THREAD

**Issue by jiri-bati-novak** [CultivateHQ/seat_saver#3]
Will this tutorial continue? The roadmap shows interesting subjects, but there is no progress... :)

**Comment by urfolomeus** [comment]
Yes! I've moved it over to the company blog so that I can write them up properly. Will update the wiki and README accordingly.

Watch #phoenixelm hashtag on Twitter or follow @cultivatehq. :)

**Comment by jiri-bati-novak** [comment]
Oh, sweet, one more reason to keep twitter app on my phone :-)
Thanks for the answer

**Comment by urfolomeus** [comment]
No problem. Thanks for asking. :)

I've updated the wiki homepage now with more info. With any luck it'll only be a day or two until the next parts are out.
