### ISSUE TITLE
elm-phoenix native channels?

### ISSUE THREAD

**Issue by kristianmandrup** [CultivateHQ/seat_saver#5]
https://github.com/svard/elm-phoenix

How about trying it out as an alternative :)

**Comment by urfolomeus** [comment]
I did have a look at that when @svard mentioned it on the elm-discuss mailing list, but not had time to try integrating it yet. Maybe in a future post! :)

**Comment by kristianmandrup** [comment]
Awesome! I might try it myself if/when I have the time ;)
