### ISSUE TITLE
ERROR (duplicate_table): relation "seats" already exists

### ISSUE THREAD

**Issue by emhoracek** [CultivateHQ/seat_saver#7]
I missed the part where you start over in Chapter 10, so I kept going through Chapter 11 with the same code. When I tried to create the seat model again, I got an error which was very puzzling until I went back and read Chapter 10 again. I deleted my seat_saver directory and cloned this repo and checked out the pre-http branch and started again from Chapter 10. But still when I migrate, I get this error.

```
$ mix ecto.migrate
Compiled web/models/seat.ex
Generated seat_saver app

12:40:38.510 [info]  == Running SeatSaver.Repo.Migrations.CreateSeat.change/0 forward

12:40:38.510 [info]  create table seats
** (Postgrex.Error) ERROR (duplicate_table): relation "seats" already exists
    (ecto) lib/ecto/adapters/sql.ex:172: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:55: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:55: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:74: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:72: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:23: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:113: Ecto.Migrator.attempt/6
    (ecto) lib/ecto/migrator.ex:63: anonymous fn/4 in Ecto.Migrator.do_up/4
    (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/3
    (ecto) lib/ecto/adapters/sql.ex:566: Ecto.Adapters.SQL.transaction/8
    (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
    (ecto) lib/ecto/adapters/sql.ex:535: Ecto.Adapters.SQL.transaction/3
    (ecto) lib/ecto/migrator.ex:218: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:62: Mix.Tasks.Ecto.Migrate.run/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Halp?

**Comment by emhoracek** [comment]
I fixed this by `sudo su postgres`, `psql seat_saver_dev` then `DROP TABLE seats;`. But this does seem to to be a gotcha, even if I got into it just by not paying enough attention.

**Comment by paulanthonywilson** [comment]
Hi @emhoracek,

Thanks for reporting this - I think I see what's going on here. If you take the API diversion in part 9, you end up with running [this migration](https://github.com/CultivateHQ/seat_saver/blob/http/priv/repo/migrations/20151105133633_create_seat.exs) which has a timestamp of "20151105133633".  When you jump back to the master branch you get [this migration](https://github.com/CultivateHQ/seat_saver/blob/master/priv/repo/migrations/20151215160750_create_seat.exs) which is identical but has a different timestamp "20151215160750".

Because Ecto uses the timestamp to determine which migrations have run, it tries to create the `seats` table again.

I think the fix is to ensure the migration is the same on all branches. What do you think @emhoracek and @urfolomeus ?

**Comment by urfolomeus** [comment]
Hi @emhoracek, sorry for the delay in getting back to you. My notifications haven't been working for some reason.

Yes, I agree with Paul. The branching is confusing. I'll take a look at a better way to deal with this.

**Comment by urfolomeus** [comment]
Hi @emhoracek. Sorry for the delay in getting this fixed. I've added a note to [Post 11](http://www.cultivatehq.com/posts/phoenix-elm-11) (scroll down to "Getting initial seat data" step 2) and given you credit. :)

Hope this resolves things?

**Comment by emhoracek** [comment]
@urfolomeus Thanks, I bet this will help some other inattentive fool in the future. :) :+1:

**Comment by urfolomeus** [comment]
@emhoracek to be fair the warning was in a separate blog post, as was the prompt to revert the code. Also there was no mention of potential issues when the error occurred.

I think the post is much better for it, so thank you for taking the time to report it :)
