### ISSUE TITLE
Typo in part 13

### ISSUE THREAD

**Issue by gonglexin** [CultivateHQ/seat_saver#8]
Section "Dealing with the request", there is a typo in `web/channels/seat_channel.ex` code snippet

`{:ok, _seat} ->` should be `{:ok, seat} ->`, otherwise, you will broadcast the original seat, not the updated one.

**Comment by urfolomeus** [comment]
Thanks @gonglexin. I'll fix that shortly. :)

**Comment by urfolomeus** [comment]
I've fixed this in the blog post now. Thanks again for raising @gonglexin. :)
